import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import { Footer } from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: 'Nextjs 14 Home',
    template: '%s | Nextjs 14',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col justify-between mx-auto px-4 sm:px-6 lg:px-8 max-w-screen-xl">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
